# permissions for end users to view clusterinsights.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterinsight-viewer-role
rules:
- apiGroups:
  - kubeeye.kubesphere.io
  resources:
  - clusterinsights
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kubeeye.kubesphere.io
  resources:
  - clusterinsights/status
  verbs:
  - get
