/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	"github.com/kubesphere/kubeeye/apis/kubeeye/v1alpha1"
	scheme2 "github.com/kubesphere/kubeeye/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ClusterInsightsGetter has a method to return a ClusterInsightInterface.
// A group's client should implement this interface.
type ClusterInsightsGetter interface {
	ClusterInsights() ClusterInsightInterface
}

// ClusterInsightInterface has methods to work with ClusterInsight resources.
type ClusterInsightInterface interface {
	Create(ctx context.Context, clusterInsight *v1alpha1.ClusterInsight, opts v1.CreateOptions) (*v1alpha1.ClusterInsight, error)
	Update(ctx context.Context, clusterInsight *v1alpha1.ClusterInsight, opts v1.UpdateOptions) (*v1alpha1.ClusterInsight, error)
	UpdateStatus(ctx context.Context, clusterInsight *v1alpha1.ClusterInsight, opts v1.UpdateOptions) (*v1alpha1.ClusterInsight, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.ClusterInsight, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.ClusterInsightList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ClusterInsight, err error)
	ClusterInsightExpansion
}

// clusterInsights implements ClusterInsightInterface
type clusterInsights struct {
	client rest.Interface
}

// newClusterInsights returns a ClusterInsights
func newClusterInsights(c *KubeeyeV1alpha1Client) *clusterInsights {
	return &clusterInsights{
		client: c.RESTClient(),
	}
}

// Get takes name of the clusterInsight, and returns the corresponding clusterInsight object, and an error if there is any.
func (c *clusterInsights) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ClusterInsight, err error) {
	result = &v1alpha1.ClusterInsight{}
	err = c.client.Get().
		Resource("clusterinsights").
		Name(name).
		VersionedParams(&options, scheme2.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ClusterInsights that match those selectors.
func (c *clusterInsights) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ClusterInsightList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.ClusterInsightList{}
	err = c.client.Get().
		Resource("clusterinsights").
		VersionedParams(&opts, scheme2.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested clusterInsights.
func (c *clusterInsights) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("clusterinsights").
		VersionedParams(&opts, scheme2.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a clusterInsight and creates it.  Returns the server's representation of the clusterInsight, and an error, if there is any.
func (c *clusterInsights) Create(ctx context.Context, clusterInsight *v1alpha1.ClusterInsight, opts v1.CreateOptions) (result *v1alpha1.ClusterInsight, err error) {
	result = &v1alpha1.ClusterInsight{}
	err = c.client.Post().
		Resource("clusterinsights").
		VersionedParams(&opts, scheme2.ParameterCodec).
		Body(clusterInsight).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a clusterInsight and updates it. Returns the server's representation of the clusterInsight, and an error, if there is any.
func (c *clusterInsights) Update(ctx context.Context, clusterInsight *v1alpha1.ClusterInsight, opts v1.UpdateOptions) (result *v1alpha1.ClusterInsight, err error) {
	result = &v1alpha1.ClusterInsight{}
	err = c.client.Put().
		Resource("clusterinsights").
		Name(clusterInsight.Name).
		VersionedParams(&opts, scheme2.ParameterCodec).
		Body(clusterInsight).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *clusterInsights) UpdateStatus(ctx context.Context, clusterInsight *v1alpha1.ClusterInsight, opts v1.UpdateOptions) (result *v1alpha1.ClusterInsight, err error) {
	result = &v1alpha1.ClusterInsight{}
	err = c.client.Put().
		Resource("clusterinsights").
		Name(clusterInsight.Name).
		SubResource("status").
		VersionedParams(&opts, scheme2.ParameterCodec).
		Body(clusterInsight).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the clusterInsight and deletes it. Returns an error if one occurs.
func (c *clusterInsights) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("clusterinsights").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *clusterInsights) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("clusterinsights").
		VersionedParams(&listOpts, scheme2.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched clusterInsight.
func (c *clusterInsights) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ClusterInsight, err error) {
	result = &v1alpha1.ClusterInsight{}
	err = c.client.Patch(pt).
		Resource("clusterinsights").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme2.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
