package conf

const (
	AppsGroup = "apps"
	NoGroup = ""
	BatchGroup = "batch"
	RoleGroup = "rbac.authorization.k8s.io"
	APIVersionV1 = "v1"
	Nodes = "nodes"
	Deployments = "deployments"
	Daemonsets = "daemonsets"
	Statefulsets = "statefulsets"
	Jobs = "jobs"
	Cronjobs = "cronjobs"
	Namespaces = "namespaces"
	Events = "events"
	Roles = "roles"
	Clusterroles = "clusterroles"
	Group    = "kubeeyeplugins.kubesphere.io"
	Version  = "v1alpha1"
	Resource = "pluginsubscriptions"
	KubeeyeNameSpace = "kubeeye-system"
	PluginIntalled     string = "installed"
	PluginInstalling   string = "installing"
	PluginUninstalled  string = "uninstalled"
)