/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha2

// InspectPlanListerExpansion allows custom methods to be added to
// InspectPlanLister.
type InspectPlanListerExpansion interface{}

// InspectPlanNamespaceListerExpansion allows custom methods to be added to
// InspectPlanNamespaceLister.
type InspectPlanNamespaceListerExpansion interface{}

// InspectResultListerExpansion allows custom methods to be added to
// InspectResultLister.
type InspectResultListerExpansion interface{}

// InspectResultNamespaceListerExpansion allows custom methods to be added to
// InspectResultNamespaceLister.
type InspectResultNamespaceListerExpansion interface{}

// InspectRuleListerExpansion allows custom methods to be added to
// InspectRuleLister.
type InspectRuleListerExpansion interface{}

// InspectRuleNamespaceListerExpansion allows custom methods to be added to
// InspectRuleNamespaceLister.
type InspectRuleNamespaceListerExpansion interface{}

// InspectTaskListerExpansion allows custom methods to be added to
// InspectTaskLister.
type InspectTaskListerExpansion interface{}

// InspectTaskNamespaceListerExpansion allows custom methods to be added to
// InspectTaskNamespaceLister.
type InspectTaskNamespaceListerExpansion interface{}
