/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha2

import (
	v1alpha2 "github.com/kubesphere/kubeeye/apis/kubeeye/v1alpha2"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// InspectPlanLister helps list InspectPlans.
// All objects returned here must be treated as read-only.
type InspectPlanLister interface {
	// List lists all InspectPlans in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha2.InspectPlan, err error)
	// InspectPlans returns an object that can list and get InspectPlans.
	InspectPlans(namespace string) InspectPlanNamespaceLister
	InspectPlanListerExpansion
}

// inspectPlanLister implements the InspectPlanLister interface.
type inspectPlanLister struct {
	indexer cache.Indexer
}

// NewInspectPlanLister returns a new InspectPlanLister.
func NewInspectPlanLister(indexer cache.Indexer) InspectPlanLister {
	return &inspectPlanLister{indexer: indexer}
}

// List lists all InspectPlans in the indexer.
func (s *inspectPlanLister) List(selector labels.Selector) (ret []*v1alpha2.InspectPlan, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha2.InspectPlan))
	})
	return ret, err
}

// InspectPlans returns an object that can list and get InspectPlans.
func (s *inspectPlanLister) InspectPlans(namespace string) InspectPlanNamespaceLister {
	return inspectPlanNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// InspectPlanNamespaceLister helps list and get InspectPlans.
// All objects returned here must be treated as read-only.
type InspectPlanNamespaceLister interface {
	// List lists all InspectPlans in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha2.InspectPlan, err error)
	// Get retrieves the InspectPlan from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha2.InspectPlan, error)
	InspectPlanNamespaceListerExpansion
}

// inspectPlanNamespaceLister implements the InspectPlanNamespaceLister
// interface.
type inspectPlanNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all InspectPlans in the indexer for a given namespace.
func (s inspectPlanNamespaceLister) List(selector labels.Selector) (ret []*v1alpha2.InspectPlan, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha2.InspectPlan))
	})
	return ret, err
}

// Get retrieves the InspectPlan from the indexer for a given namespace and name.
func (s inspectPlanNamespaceLister) Get(name string) (*v1alpha2.InspectPlan, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha2.Resource("inspectplan"), name)
	}
	return obj.(*v1alpha2.InspectPlan), nil
}
