/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha2

import (
	kubeeyev1alpha2 "github.com/kubesphere/kubeeye/apis/kubeeye/v1alpha2"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// InspectRuleLister helps list InspectRules.
// All objects returned here must be treated as read-only.
type InspectRuleLister interface {
	// List lists all InspectRules in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*kubeeyev1alpha2.InspectRule, err error)
	// Get retrieves the InspectRule from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*kubeeyev1alpha2.InspectRule, error)
	InspectRuleListerExpansion
}

// inspectRuleLister implements the InspectRuleLister interface.
type inspectRuleLister struct {
	listers.ResourceIndexer[*kubeeyev1alpha2.InspectRule]
}

// NewInspectRuleLister returns a new InspectRuleLister.
func NewInspectRuleLister(indexer cache.Indexer) InspectRuleLister {
	return &inspectRuleLister{listers.New[*kubeeyev1alpha2.InspectRule](indexer, kubeeyev1alpha2.Resource("inspectrule"))}
}
