/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha2 "github.com/kubesphere/kubeeye/apis/kubeeye/v1alpha2"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeInspectRules implements InspectRuleInterface
type FakeInspectRules struct {
	Fake *FakeKubeeyeV1alpha2
	ns   string
}

var inspectrulesResource = schema.GroupVersionResource{Group: "kubeeye", Version: "v1alpha2", Resource: "inspectrules"}

var inspectrulesKind = schema.GroupVersionKind{Group: "kubeeye", Version: "v1alpha2", Kind: "InspectRule"}

// Get takes name of the inspectRule, and returns the corresponding inspectRule object, and an error if there is any.
func (c *FakeInspectRules) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha2.InspectRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(inspectrulesResource, c.ns, name), &v1alpha2.InspectRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.InspectRule), err
}

// List takes label and field selectors, and returns the list of InspectRules that match those selectors.
func (c *FakeInspectRules) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha2.InspectRuleList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(inspectrulesResource, inspectrulesKind, c.ns, opts), &v1alpha2.InspectRuleList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha2.InspectRuleList{ListMeta: obj.(*v1alpha2.InspectRuleList).ListMeta}
	for _, item := range obj.(*v1alpha2.InspectRuleList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested inspectRules.
func (c *FakeInspectRules) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(inspectrulesResource, c.ns, opts))

}

// Create takes the representation of a inspectRule and creates it.  Returns the server's representation of the inspectRule, and an error, if there is any.
func (c *FakeInspectRules) Create(ctx context.Context, inspectRule *v1alpha2.InspectRule, opts v1.CreateOptions) (result *v1alpha2.InspectRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(inspectrulesResource, c.ns, inspectRule), &v1alpha2.InspectRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.InspectRule), err
}

// Update takes the representation of a inspectRule and updates it. Returns the server's representation of the inspectRule, and an error, if there is any.
func (c *FakeInspectRules) Update(ctx context.Context, inspectRule *v1alpha2.InspectRule, opts v1.UpdateOptions) (result *v1alpha2.InspectRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(inspectrulesResource, c.ns, inspectRule), &v1alpha2.InspectRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.InspectRule), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeInspectRules) UpdateStatus(ctx context.Context, inspectRule *v1alpha2.InspectRule, opts v1.UpdateOptions) (*v1alpha2.InspectRule, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(inspectrulesResource, "status", c.ns, inspectRule), &v1alpha2.InspectRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.InspectRule), err
}

// Delete takes name of the inspectRule and deletes it. Returns an error if one occurs.
func (c *FakeInspectRules) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(inspectrulesResource, c.ns, name, opts), &v1alpha2.InspectRule{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeInspectRules) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(inspectrulesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha2.InspectRuleList{})
	return err
}

// Patch applies the patch and returns the patched inspectRule.
func (c *FakeInspectRules) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha2.InspectRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(inspectrulesResource, c.ns, name, pt, data, subresources...), &v1alpha2.InspectRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.InspectRule), err
}
