/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha2 "github.com/kubesphere/kubeeye/apis/kubeeye/v1alpha2"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeInspectRuleses implements InspectRulesInterface
type FakeInspectRuleses struct {
	Fake *FakeKubeeyeV1alpha2
	ns   string
}

var inspectrulesesResource = schema.GroupVersionResource{Group: "kubeeye.kubesphere.io", Version: "v1alpha2", Resource: "inspectrules"}

var inspectrulesesKind = schema.GroupVersionKind{Group: "kubeeye.kubesphere.io", Version: "v1alpha2", Kind: "InspectRules"}

// Get takes name of the inspectRules, and returns the corresponding inspectRules object, and an error if there is any.
func (c *FakeInspectRuleses) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha2.InspectRules, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(inspectrulesesResource, c.ns, name), &v1alpha2.InspectRules{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.InspectRules), err
}

// List takes label and field selectors, and returns the list of InspectRules that match those selectors.
func (c *FakeInspectRuleses) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha2.InspectRulesList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(inspectrulesesResource, inspectrulesesKind, c.ns, opts), &v1alpha2.InspectRulesList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha2.InspectRulesList{ListMeta: obj.(*v1alpha2.InspectRulesList).ListMeta}
	for _, item := range obj.(*v1alpha2.InspectRulesList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested inspectRuleses.
func (c *FakeInspectRuleses) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(inspectrulesesResource, c.ns, opts))

}

// Create takes the representation of a inspectRules and creates it.  Returns the server's representation of the inspectRules, and an error, if there is any.
func (c *FakeInspectRuleses) Create(ctx context.Context, inspectRules *v1alpha2.InspectRules, opts v1.CreateOptions) (result *v1alpha2.InspectRules, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(inspectrulesesResource, c.ns, inspectRules), &v1alpha2.InspectRules{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.InspectRules), err
}

// Update takes the representation of a inspectRules and updates it. Returns the server's representation of the inspectRules, and an error, if there is any.
func (c *FakeInspectRuleses) Update(ctx context.Context, inspectRules *v1alpha2.InspectRules, opts v1.UpdateOptions) (result *v1alpha2.InspectRules, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(inspectrulesesResource, c.ns, inspectRules), &v1alpha2.InspectRules{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.InspectRules), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeInspectRuleses) UpdateStatus(ctx context.Context, inspectRules *v1alpha2.InspectRules, opts v1.UpdateOptions) (*v1alpha2.InspectRules, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(inspectrulesesResource, "status", c.ns, inspectRules), &v1alpha2.InspectRules{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.InspectRules), err
}

// Delete takes name of the inspectRules and deletes it. Returns an error if one occurs.
func (c *FakeInspectRuleses) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(inspectrulesesResource, c.ns, name, opts), &v1alpha2.InspectRules{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeInspectRuleses) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(inspectrulesesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha2.InspectRulesList{})
	return err
}

// Patch applies the patch and returns the patched inspectRules.
func (c *FakeInspectRuleses) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha2.InspectRules, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(inspectrulesesResource, c.ns, name, pt, data, subresources...), &v1alpha2.InspectRules{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.InspectRules), err
}
