/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha2 "github.com/kubesphere/kubeeye/apis/kubeeye/v1alpha2"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeInspectPlans implements InspectPlanInterface
type FakeInspectPlans struct {
	Fake *FakeKubeeyeV1alpha2
}

var inspectplansResource = schema.GroupVersionResource{Group: "kubeeye", Version: "v1alpha2", Resource: "inspectplans"}

var inspectplansKind = schema.GroupVersionKind{Group: "kubeeye", Version: "v1alpha2", Kind: "InspectPlan"}

// Get takes name of the inspectPlan, and returns the corresponding inspectPlan object, and an error if there is any.
func (c *FakeInspectPlans) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha2.InspectPlan, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(inspectplansResource, name), &v1alpha2.InspectPlan{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.InspectPlan), err
}

// List takes label and field selectors, and returns the list of InspectPlans that match those selectors.
func (c *FakeInspectPlans) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha2.InspectPlanList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(inspectplansResource, inspectplansKind, opts), &v1alpha2.InspectPlanList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha2.InspectPlanList{ListMeta: obj.(*v1alpha2.InspectPlanList).ListMeta}
	for _, item := range obj.(*v1alpha2.InspectPlanList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested inspectPlans.
func (c *FakeInspectPlans) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(inspectplansResource, opts))
}

// Create takes the representation of a inspectPlan and creates it.  Returns the server's representation of the inspectPlan, and an error, if there is any.
func (c *FakeInspectPlans) Create(ctx context.Context, inspectPlan *v1alpha2.InspectPlan, opts v1.CreateOptions) (result *v1alpha2.InspectPlan, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(inspectplansResource, inspectPlan), &v1alpha2.InspectPlan{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.InspectPlan), err
}

// Update takes the representation of a inspectPlan and updates it. Returns the server's representation of the inspectPlan, and an error, if there is any.
func (c *FakeInspectPlans) Update(ctx context.Context, inspectPlan *v1alpha2.InspectPlan, opts v1.UpdateOptions) (result *v1alpha2.InspectPlan, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(inspectplansResource, inspectPlan), &v1alpha2.InspectPlan{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.InspectPlan), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeInspectPlans) UpdateStatus(ctx context.Context, inspectPlan *v1alpha2.InspectPlan, opts v1.UpdateOptions) (*v1alpha2.InspectPlan, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(inspectplansResource, "status", inspectPlan), &v1alpha2.InspectPlan{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.InspectPlan), err
}

// Delete takes name of the inspectPlan and deletes it. Returns an error if one occurs.
func (c *FakeInspectPlans) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(inspectplansResource, name, opts), &v1alpha2.InspectPlan{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeInspectPlans) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(inspectplansResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha2.InspectPlanList{})
	return err
}

// Patch applies the patch and returns the patched inspectPlan.
func (c *FakeInspectPlans) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha2.InspectPlan, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(inspectplansResource, name, pt, data, subresources...), &v1alpha2.InspectPlan{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.InspectPlan), err
}
