/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha2 "github.com/kubesphere/kubeeye-v1alpha2/apis/kubeeye/v1alpha2"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeInspectTasks implements InspectTaskInterface
type FakeInspectTasks struct {
	Fake *FakeKubeeyeV1alpha2
}

var inspecttasksResource = schema.GroupVersionResource{Group: "kubeeye", Version: "v1alpha2", Resource: "inspecttasks"}

var inspecttasksKind = schema.GroupVersionKind{Group: "kubeeye", Version: "v1alpha2", Kind: "InspectTask"}

// Get takes name of the inspectTask, and returns the corresponding inspectTask object, and an error if there is any.
func (c *FakeInspectTasks) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha2.InspectTask, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(inspecttasksResource, name), &v1alpha2.InspectTask{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.InspectTask), err
}

// List takes label and field selectors, and returns the list of InspectTasks that match those selectors.
func (c *FakeInspectTasks) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha2.InspectTaskList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(inspecttasksResource, inspecttasksKind, opts), &v1alpha2.InspectTaskList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha2.InspectTaskList{ListMeta: obj.(*v1alpha2.InspectTaskList).ListMeta}
	for _, item := range obj.(*v1alpha2.InspectTaskList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested inspectTasks.
func (c *FakeInspectTasks) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(inspecttasksResource, opts))
}

// Create takes the representation of a inspectTask and creates it.  Returns the server's representation of the inspectTask, and an error, if there is any.
func (c *FakeInspectTasks) Create(ctx context.Context, inspectTask *v1alpha2.InspectTask, opts v1.CreateOptions) (result *v1alpha2.InspectTask, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(inspecttasksResource, inspectTask), &v1alpha2.InspectTask{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.InspectTask), err
}

// Update takes the representation of a inspectTask and updates it. Returns the server's representation of the inspectTask, and an error, if there is any.
func (c *FakeInspectTasks) Update(ctx context.Context, inspectTask *v1alpha2.InspectTask, opts v1.UpdateOptions) (result *v1alpha2.InspectTask, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(inspecttasksResource, inspectTask), &v1alpha2.InspectTask{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.InspectTask), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeInspectTasks) UpdateStatus(ctx context.Context, inspectTask *v1alpha2.InspectTask, opts v1.UpdateOptions) (*v1alpha2.InspectTask, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(inspecttasksResource, "status", inspectTask), &v1alpha2.InspectTask{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.InspectTask), err
}

// Delete takes name of the inspectTask and deletes it. Returns an error if one occurs.
func (c *FakeInspectTasks) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(inspecttasksResource, name, opts), &v1alpha2.InspectTask{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeInspectTasks) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(inspecttasksResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha2.InspectTaskList{})
	return err
}

// Patch applies the patch and returns the patched inspectTask.
func (c *FakeInspectTasks) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha2.InspectTask, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(inspecttasksResource, name, pt, data, subresources...), &v1alpha2.InspectTask{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.InspectTask), err
}
