//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha2

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterInfo) DeepCopyInto(out *ClusterInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterInfo.
func (in *ClusterInfo) DeepCopy() *ClusterInfo {
	if in == nil {
		return nil
	}
	out := new(ClusterInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentResultItem) DeepCopyInto(out *ComponentResultItem) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentResultItem.
func (in *ComponentResultItem) DeepCopy() *ComponentResultItem {
	if in == nil {
		return nil
	}
	out := new(ComponentResultItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExtraInfo) DeepCopyInto(out *ExtraInfo) {
	*out = *in
	if in.NamespacesList != nil {
		in, out := &in.NamespacesList, &out.NamespacesList
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExtraInfo.
func (in *ExtraInfo) DeepCopy() *ExtraInfo {
	if in == nil {
		return nil
	}
	out := new(ExtraInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FileChangeResultItem) DeepCopyInto(out *FileChangeResultItem) {
	*out = *in
	if in.Issues != nil {
		in, out := &in.Issues, &out.Issues
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FileChangeResultItem.
func (in *FileChangeResultItem) DeepCopy() *FileChangeResultItem {
	if in == nil {
		return nil
	}
	out := new(FileChangeResultItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FileChangeRule) DeepCopyInto(out *FileChangeRule) {
	*out = *in
	in.RuleItemBases.DeepCopyInto(&out.RuleItemBases)
	if in.NodeName != nil {
		in, out := &in.NodeName, &out.NodeName
		*out = new(string)
		**out = **in
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FileChangeRule.
func (in *FileChangeRule) DeepCopy() *FileChangeRule {
	if in == nil {
		return nil
	}
	out := new(FileChangeRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FileFilterRule) DeepCopyInto(out *FileFilterRule) {
	*out = *in
	in.RuleItemBases.DeepCopyInto(&out.RuleItemBases)
	if in.NodeName != nil {
		in, out := &in.NodeName, &out.NodeName
		*out = new(string)
		**out = **in
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FileFilterRule.
func (in *FileFilterRule) DeepCopy() *FileFilterRule {
	if in == nil {
		return nil
	}
	out := new(FileFilterRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InspectPlan) DeepCopyInto(out *InspectPlan) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InspectPlan.
func (in *InspectPlan) DeepCopy() *InspectPlan {
	if in == nil {
		return nil
	}
	out := new(InspectPlan)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InspectPlan) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InspectPlanList) DeepCopyInto(out *InspectPlanList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]InspectPlan, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InspectPlanList.
func (in *InspectPlanList) DeepCopy() *InspectPlanList {
	if in == nil {
		return nil
	}
	out := new(InspectPlanList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InspectPlanList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InspectPlanSpec) DeepCopyInto(out *InspectPlanSpec) {
	*out = *in
	if in.Schedule != nil {
		in, out := &in.Schedule, &out.Schedule
		*out = new(string)
		**out = **in
	}
	if in.RuleNames != nil {
		in, out := &in.RuleNames, &out.RuleNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InspectPlanSpec.
func (in *InspectPlanSpec) DeepCopy() *InspectPlanSpec {
	if in == nil {
		return nil
	}
	out := new(InspectPlanSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InspectPlanStatus) DeepCopyInto(out *InspectPlanStatus) {
	*out = *in
	in.LastScheduleTime.DeepCopyInto(&out.LastScheduleTime)
	if in.TaskNames != nil {
		in, out := &in.TaskNames, &out.TaskNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.NextScheduleTime.DeepCopyInto(&out.NextScheduleTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InspectPlanStatus.
func (in *InspectPlanStatus) DeepCopy() *InspectPlanStatus {
	if in == nil {
		return nil
	}
	out := new(InspectPlanStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InspectResult) DeepCopyInto(out *InspectResult) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InspectResult.
func (in *InspectResult) DeepCopy() *InspectResult {
	if in == nil {
		return nil
	}
	out := new(InspectResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InspectResult) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InspectResultList) DeepCopyInto(out *InspectResultList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]InspectResult, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InspectResultList.
func (in *InspectResultList) DeepCopy() *InspectResultList {
	if in == nil {
		return nil
	}
	out := new(InspectResultList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InspectResultList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InspectResultSpec) DeepCopyInto(out *InspectResultSpec) {
	*out = *in
	if in.PrometheusResult != nil {
		in, out := &in.PrometheusResult, &out.PrometheusResult
		*out = make([][]map[string]string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = make([]map[string]string, len(*in))
				for i := range *in {
					if (*in)[i] != nil {
						in, out := &(*in)[i], &(*out)[i]
						*out = make(map[string]string, len(*in))
						for key, val := range *in {
							(*out)[key] = val
						}
					}
				}
			}
		}
	}
	in.OpaResult.DeepCopyInto(&out.OpaResult)
	if in.NodeInfoResult != nil {
		in, out := &in.NodeInfoResult, &out.NodeInfoResult
		*out = make(map[string]NodeInfoResult, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.FilterResult != nil {
		in, out := &in.FilterResult, &out.FilterResult
		*out = make(map[string][]FileChangeResultItem, len(*in))
		for key, val := range *in {
			var outVal []FileChangeResultItem
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = make([]FileChangeResultItem, len(*in))
				for i := range *in {
					(*in)[i].DeepCopyInto(&(*out)[i])
				}
			}
			(*out)[key] = outVal
		}
	}
	if in.ComponentResult != nil {
		in, out := &in.ComponentResult, &out.ComponentResult
		*out = make([]ComponentResultItem, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InspectResultSpec.
func (in *InspectResultSpec) DeepCopy() *InspectResultSpec {
	if in == nil {
		return nil
	}
	out := new(InspectResultSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InspectResultStatus) DeepCopyInto(out *InspectResultStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InspectResultStatus.
func (in *InspectResultStatus) DeepCopy() *InspectResultStatus {
	if in == nil {
		return nil
	}
	out := new(InspectResultStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InspectRule) DeepCopyInto(out *InspectRule) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InspectRule.
func (in *InspectRule) DeepCopy() *InspectRule {
	if in == nil {
		return nil
	}
	out := new(InspectRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InspectRule) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InspectRuleList) DeepCopyInto(out *InspectRuleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]InspectRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InspectRuleList.
func (in *InspectRuleList) DeepCopy() *InspectRuleList {
	if in == nil {
		return nil
	}
	out := new(InspectRuleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InspectRuleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InspectRuleSpec) DeepCopyInto(out *InspectRuleSpec) {
	*out = *in
	if in.Opas != nil {
		in, out := &in.Opas, &out.Opas
		*out = make([]OpaRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Prometheus != nil {
		in, out := &in.Prometheus, &out.Prometheus
		*out = make([]PrometheusRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.FileChange != nil {
		in, out := &in.FileChange, &out.FileChange
		*out = make([]FileChangeRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Sysctl != nil {
		in, out := &in.Sysctl, &out.Sysctl
		*out = make([]SysRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Systemd != nil {
		in, out := &in.Systemd, &out.Systemd
		*out = make([]SysRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.FileFilter != nil {
		in, out := &in.FileFilter, &out.FileFilter
		*out = make([]FileFilterRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Component != nil {
		in, out := &in.Component, &out.Component
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InspectRuleSpec.
func (in *InspectRuleSpec) DeepCopy() *InspectRuleSpec {
	if in == nil {
		return nil
	}
	out := new(InspectRuleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InspectRuleStatus) DeepCopyInto(out *InspectRuleStatus) {
	*out = *in
	in.ImportTime.DeepCopyInto(&out.ImportTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InspectRuleStatus.
func (in *InspectRuleStatus) DeepCopy() *InspectRuleStatus {
	if in == nil {
		return nil
	}
	out := new(InspectRuleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InspectTask) DeepCopyInto(out *InspectTask) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InspectTask.
func (in *InspectTask) DeepCopy() *InspectTask {
	if in == nil {
		return nil
	}
	out := new(InspectTask)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InspectTask) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InspectTaskList) DeepCopyInto(out *InspectTaskList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]InspectTask, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InspectTaskList.
func (in *InspectTaskList) DeepCopy() *InspectTaskList {
	if in == nil {
		return nil
	}
	out := new(InspectTaskList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InspectTaskList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InspectTaskSpec) DeepCopyInto(out *InspectTaskSpec) {
	*out = *in
	if in.InspectRuleTotal != nil {
		in, out := &in.InspectRuleTotal, &out.InspectRuleTotal
		*out = make(map[string]int, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]JobRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InspectTaskSpec.
func (in *InspectTaskSpec) DeepCopy() *InspectTaskSpec {
	if in == nil {
		return nil
	}
	out := new(InspectTaskSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InspectTaskStatus) DeepCopyInto(out *InspectTaskStatus) {
	*out = *in
	out.ClusterInfo = in.ClusterInfo
	if in.JobPhase != nil {
		in, out := &in.JobPhase, &out.JobPhase
		*out = make([]JobPhase, len(*in))
		copy(*out, *in)
	}
	if in.StartTimestamp != nil {
		in, out := &in.StartTimestamp, &out.StartTimestamp
		*out = (*in).DeepCopy()
	}
	if in.EndTimestamp != nil {
		in, out := &in.EndTimestamp, &out.EndTimestamp
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InspectTaskStatus.
func (in *InspectTaskStatus) DeepCopy() *InspectTaskStatus {
	if in == nil {
		return nil
	}
	out := new(InspectTaskStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JobPhase) DeepCopyInto(out *JobPhase) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JobPhase.
func (in *JobPhase) DeepCopy() *JobPhase {
	if in == nil {
		return nil
	}
	out := new(JobPhase)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JobRule) DeepCopyInto(out *JobRule) {
	*out = *in
	if in.RunRule != nil {
		in, out := &in.RunRule, &out.RunRule
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JobRule.
func (in *JobRule) DeepCopy() *JobRule {
	if in == nil {
		return nil
	}
	out := new(JobRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeeyeOpaResult) DeepCopyInto(out *KubeeyeOpaResult) {
	*out = *in
	out.ScoreInfo = in.ScoreInfo
	if in.ResourceResults != nil {
		in, out := &in.ResourceResults, &out.ResourceResults
		*out = make([]ResourceResult, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.ExtraInfo.DeepCopyInto(&out.ExtraInfo)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeeyeOpaResult.
func (in *KubeeyeOpaResult) DeepCopy() *KubeeyeOpaResult {
	if in == nil {
		return nil
	}
	out := new(KubeeyeOpaResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeInfoResult) DeepCopyInto(out *NodeInfoResult) {
	*out = *in
	if in.NodeInfo != nil {
		in, out := &in.NodeInfo, &out.NodeInfo
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.FileChangeResult != nil {
		in, out := &in.FileChangeResult, &out.FileChangeResult
		*out = make([]FileChangeResultItem, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SysctlResult != nil {
		in, out := &in.SysctlResult, &out.SysctlResult
		*out = make([]NodeResultItem, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SystemdResult != nil {
		in, out := &in.SystemdResult, &out.SystemdResult
		*out = make([]NodeResultItem, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeInfoResult.
func (in *NodeInfoResult) DeepCopy() *NodeInfoResult {
	if in == nil {
		return nil
	}
	out := new(NodeInfoResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeResultItem) DeepCopyInto(out *NodeResultItem) {
	*out = *in
	if in.Assert != nil {
		in, out := &in.Assert, &out.Assert
		*out = new(bool)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeResultItem.
func (in *NodeResultItem) DeepCopy() *NodeResultItem {
	if in == nil {
		return nil
	}
	out := new(NodeResultItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpaRule) DeepCopyInto(out *OpaRule) {
	*out = *in
	in.RuleItemBases.DeepCopyInto(&out.RuleItemBases)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpaRule.
func (in *OpaRule) DeepCopy() *OpaRule {
	if in == nil {
		return nil
	}
	out := new(OpaRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrometheusRule) DeepCopyInto(out *PrometheusRule) {
	*out = *in
	in.RuleItemBases.DeepCopyInto(&out.RuleItemBases)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrometheusRule.
func (in *PrometheusRule) DeepCopy() *PrometheusRule {
	if in == nil {
		return nil
	}
	out := new(PrometheusRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceResult) DeepCopyInto(out *ResourceResult) {
	*out = *in
	if in.ResultItems != nil {
		in, out := &in.ResultItems, &out.ResultItems
		*out = make([]ResultItem, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceResult.
func (in *ResourceResult) DeepCopy() *ResourceResult {
	if in == nil {
		return nil
	}
	out := new(ResourceResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResultItem) DeepCopyInto(out *ResultItem) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResultItem.
func (in *ResultItem) DeepCopy() *ResultItem {
	if in == nil {
		return nil
	}
	out := new(ResultItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuleItemBases) DeepCopyInto(out *RuleItemBases) {
	*out = *in
	if in.Rule != nil {
		in, out := &in.Rule, &out.Rule
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuleItemBases.
func (in *RuleItemBases) DeepCopy() *RuleItemBases {
	if in == nil {
		return nil
	}
	out := new(RuleItemBases)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScoreInfo) DeepCopyInto(out *ScoreInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScoreInfo.
func (in *ScoreInfo) DeepCopy() *ScoreInfo {
	if in == nil {
		return nil
	}
	out := new(ScoreInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SysRule) DeepCopyInto(out *SysRule) {
	*out = *in
	in.RuleItemBases.DeepCopyInto(&out.RuleItemBases)
	if in.NodeName != nil {
		in, out := &in.NodeName, &out.NodeName
		*out = new(string)
		**out = **in
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SysRule.
func (in *SysRule) DeepCopy() *SysRule {
	if in == nil {
		return nil
	}
	out := new(SysRule)
	in.DeepCopyInto(out)
	return out
}
