/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha2

import (
	kubeeyev1alpha2 "github.com/kubesphere/kubeeye/apis/kubeeye/v1alpha2"
)

// BaseResultApplyConfiguration represents a declarative configuration of the BaseResult type for use
// with apply.
type BaseResultApplyConfiguration struct {
	Name   *string                `json:"name,omitempty"`
	Assert *bool                  `json:"assert,omitempty"`
	Level  *kubeeyev1alpha2.Level `json:"level,omitempty"`
}

// BaseResultApplyConfiguration constructs a declarative configuration of the BaseResult type for use with
// apply.
func BaseResult() *BaseResultApplyConfiguration {
	return &BaseResultApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *BaseResultApplyConfiguration) WithName(value string) *BaseResultApplyConfiguration {
	b.Name = &value
	return b
}

// WithAssert sets the Assert field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Assert field is set to the value of the last call.
func (b *BaseResultApplyConfiguration) WithAssert(value bool) *BaseResultApplyConfiguration {
	b.Assert = &value
	return b
}

// WithLevel sets the Level field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Level field is set to the value of the last call.
func (b *BaseResultApplyConfiguration) WithLevel(value kubeeyev1alpha2.Level) *BaseResultApplyConfiguration {
	b.Level = &value
	return b
}
