/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha2

// ClusterInfoApplyConfiguration represents a declarative configuration of the ClusterInfo type for use
// with apply.
type ClusterInfoApplyConfiguration struct {
	ClusterVersion  *string `json:"version,omitempty"`
	NodesCount      *int    `json:"nodesCount,omitempty"`
	NamespacesCount *int    `json:"namespacesCount,omitempty"`
}

// ClusterInfoApplyConfiguration constructs a declarative configuration of the ClusterInfo type for use with
// apply.
func ClusterInfo() *ClusterInfoApplyConfiguration {
	return &ClusterInfoApplyConfiguration{}
}

// WithClusterVersion sets the ClusterVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClusterVersion field is set to the value of the last call.
func (b *ClusterInfoApplyConfiguration) WithClusterVersion(value string) *ClusterInfoApplyConfiguration {
	b.ClusterVersion = &value
	return b
}

// WithNodesCount sets the NodesCount field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NodesCount field is set to the value of the last call.
func (b *ClusterInfoApplyConfiguration) WithNodesCount(value int) *ClusterInfoApplyConfiguration {
	b.NodesCount = &value
	return b
}

// WithNamespacesCount sets the NamespacesCount field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NamespacesCount field is set to the value of the last call.
func (b *ClusterInfoApplyConfiguration) WithNamespacesCount(value int) *ClusterInfoApplyConfiguration {
	b.NamespacesCount = &value
	return b
}
