/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha2

// ExtraInfoApplyConfiguration represents a declarative configuration of the ExtraInfo type for use
// with apply.
type ExtraInfoApplyConfiguration struct {
	WorkloadsCount *int     `json:"workloadsCount,omitempty"`
	NamespacesList []string `json:"namespacesList,omitempty"`
}

// ExtraInfoApplyConfiguration constructs a declarative configuration of the ExtraInfo type for use with
// apply.
func ExtraInfo() *ExtraInfoApplyConfiguration {
	return &ExtraInfoApplyConfiguration{}
}

// WithWorkloadsCount sets the WorkloadsCount field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the WorkloadsCount field is set to the value of the last call.
func (b *ExtraInfoApplyConfiguration) WithWorkloadsCount(value int) *ExtraInfoApplyConfiguration {
	b.WorkloadsCount = &value
	return b
}

// WithNamespacesList adds the given value to the NamespacesList field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the NamespacesList field.
func (b *ExtraInfoApplyConfiguration) WithNamespacesList(values ...string) *ExtraInfoApplyConfiguration {
	for i := range values {
		b.NamespacesList = append(b.NamespacesList, values[i])
	}
	return b
}
