/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha2

import (
	kubeeyev1alpha2 "github.com/kubesphere/kubeeye/apis/kubeeye/v1alpha2"
)

// FileChangeResultItemApplyConfiguration represents a declarative configuration of the FileChangeResultItem type for use
// with apply.
type FileChangeResultItemApplyConfiguration struct {
	BaseResultApplyConfiguration `json:",inline"`
	Issues                       []string `json:"issues,omitempty"`
	Path                         *string  `json:"path,omitempty"`
	NodeName                     *string  `json:"nodeName,omitempty"`
}

// FileChangeResultItemApplyConfiguration constructs a declarative configuration of the FileChangeResultItem type for use with
// apply.
func FileChangeResultItem() *FileChangeResultItemApplyConfiguration {
	return &FileChangeResultItemApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *FileChangeResultItemApplyConfiguration) WithName(value string) *FileChangeResultItemApplyConfiguration {
	b.BaseResultApplyConfiguration.Name = &value
	return b
}

// WithAssert sets the Assert field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Assert field is set to the value of the last call.
func (b *FileChangeResultItemApplyConfiguration) WithAssert(value bool) *FileChangeResultItemApplyConfiguration {
	b.BaseResultApplyConfiguration.Assert = &value
	return b
}

// WithLevel sets the Level field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Level field is set to the value of the last call.
func (b *FileChangeResultItemApplyConfiguration) WithLevel(value kubeeyev1alpha2.Level) *FileChangeResultItemApplyConfiguration {
	b.BaseResultApplyConfiguration.Level = &value
	return b
}

// WithIssues adds the given value to the Issues field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Issues field.
func (b *FileChangeResultItemApplyConfiguration) WithIssues(values ...string) *FileChangeResultItemApplyConfiguration {
	for i := range values {
		b.Issues = append(b.Issues, values[i])
	}
	return b
}

// WithPath sets the Path field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Path field is set to the value of the last call.
func (b *FileChangeResultItemApplyConfiguration) WithPath(value string) *FileChangeResultItemApplyConfiguration {
	b.Path = &value
	return b
}

// WithNodeName sets the NodeName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NodeName field is set to the value of the last call.
func (b *FileChangeResultItemApplyConfiguration) WithNodeName(value string) *FileChangeResultItemApplyConfiguration {
	b.NodeName = &value
	return b
}
