/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha2

import (
	kubeeyev1alpha2 "github.com/kubesphere/kubeeye/apis/kubeeye/v1alpha2"
)

// NodeInfoResultItemApplyConfiguration represents a declarative configuration of the NodeInfoResultItem type for use
// with apply.
type NodeInfoResultItemApplyConfiguration struct {
	BaseResultApplyConfiguration `json:",inline"`
	ResourcesType                *ResourcesTypeApplyConfiguration `json:",inline"`
	Value                        *string                          `json:"value,omitempty"`
	NodeName                     *string                          `json:"nodeName,omitempty"`
}

// NodeInfoResultItemApplyConfiguration constructs a declarative configuration of the NodeInfoResultItem type for use with
// apply.
func NodeInfoResultItem() *NodeInfoResultItemApplyConfiguration {
	return &NodeInfoResultItemApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *NodeInfoResultItemApplyConfiguration) WithName(value string) *NodeInfoResultItemApplyConfiguration {
	b.BaseResultApplyConfiguration.Name = &value
	return b
}

// WithAssert sets the Assert field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Assert field is set to the value of the last call.
func (b *NodeInfoResultItemApplyConfiguration) WithAssert(value bool) *NodeInfoResultItemApplyConfiguration {
	b.BaseResultApplyConfiguration.Assert = &value
	return b
}

// WithLevel sets the Level field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Level field is set to the value of the last call.
func (b *NodeInfoResultItemApplyConfiguration) WithLevel(value kubeeyev1alpha2.Level) *NodeInfoResultItemApplyConfiguration {
	b.BaseResultApplyConfiguration.Level = &value
	return b
}

// WithResourcesType sets the ResourcesType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ResourcesType field is set to the value of the last call.
func (b *NodeInfoResultItemApplyConfiguration) WithResourcesType(value *ResourcesTypeApplyConfiguration) *NodeInfoResultItemApplyConfiguration {
	b.ResourcesType = value
	return b
}

// WithValue sets the Value field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Value field is set to the value of the last call.
func (b *NodeInfoResultItemApplyConfiguration) WithValue(value string) *NodeInfoResultItemApplyConfiguration {
	b.Value = &value
	return b
}

// WithNodeName sets the NodeName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NodeName field is set to the value of the last call.
func (b *NodeInfoResultItemApplyConfiguration) WithNodeName(value string) *NodeInfoResultItemApplyConfiguration {
	b.NodeName = &value
	return b
}
