/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha2

import (
	kubeeyev1alpha2 "github.com/kubesphere/kubeeye/apis/kubeeye/v1alpha2"
)

// PrometheusResultApplyConfiguration represents a declarative configuration of the PrometheusResult type for use
// with apply.
type PrometheusResultApplyConfiguration struct {
	BaseResultApplyConfiguration `json:",inline"`
	Result                       *string `json:"result,omitempty"`
	RawDataEnabled               *bool   `json:"rawDataEnabled,omitempty"`
	Rule                         *string `json:"rule,omitempty"`
}

// PrometheusResultApplyConfiguration constructs a declarative configuration of the PrometheusResult type for use with
// apply.
func PrometheusResult() *PrometheusResultApplyConfiguration {
	return &PrometheusResultApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *PrometheusResultApplyConfiguration) WithName(value string) *PrometheusResultApplyConfiguration {
	b.BaseResultApplyConfiguration.Name = &value
	return b
}

// WithAssert sets the Assert field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Assert field is set to the value of the last call.
func (b *PrometheusResultApplyConfiguration) WithAssert(value bool) *PrometheusResultApplyConfiguration {
	b.BaseResultApplyConfiguration.Assert = &value
	return b
}

// WithLevel sets the Level field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Level field is set to the value of the last call.
func (b *PrometheusResultApplyConfiguration) WithLevel(value kubeeyev1alpha2.Level) *PrometheusResultApplyConfiguration {
	b.BaseResultApplyConfiguration.Level = &value
	return b
}

// WithResult sets the Result field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Result field is set to the value of the last call.
func (b *PrometheusResultApplyConfiguration) WithResult(value string) *PrometheusResultApplyConfiguration {
	b.Result = &value
	return b
}

// WithRawDataEnabled sets the RawDataEnabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RawDataEnabled field is set to the value of the last call.
func (b *PrometheusResultApplyConfiguration) WithRawDataEnabled(value bool) *PrometheusResultApplyConfiguration {
	b.RawDataEnabled = &value
	return b
}

// WithRule sets the Rule field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Rule field is set to the value of the last call.
func (b *PrometheusResultApplyConfiguration) WithRule(value string) *PrometheusResultApplyConfiguration {
	b.Rule = &value
	return b
}
