/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha2

import (
	kubeeyev1alpha2 "github.com/kubesphere/kubeeye/apis/kubeeye/v1alpha2"
)

// PrometheusRuleApplyConfiguration represents a declarative configuration of the PrometheusRule type for use
// with apply.
type PrometheusRuleApplyConfiguration struct {
	RuleItemBasesApplyConfiguration `json:",inline"`
	Prometheus                      *PrometheusConfigApplyConfiguration `json:"prometheus,omitempty"`
	RawDataEnabled                  *bool                               `json:"rawDataEnabled,omitempty"`
}

// PrometheusRuleApplyConfiguration constructs a declarative configuration of the PrometheusRule type for use with
// apply.
func PrometheusRule() *PrometheusRuleApplyConfiguration {
	return &PrometheusRuleApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *PrometheusRuleApplyConfiguration) WithName(value string) *PrometheusRuleApplyConfiguration {
	b.RuleItemBasesApplyConfiguration.Name = &value
	return b
}

// WithRule sets the Rule field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Rule field is set to the value of the last call.
func (b *PrometheusRuleApplyConfiguration) WithRule(value string) *PrometheusRuleApplyConfiguration {
	b.RuleItemBasesApplyConfiguration.Rule = &value
	return b
}

// WithDesc sets the Desc field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Desc field is set to the value of the last call.
func (b *PrometheusRuleApplyConfiguration) WithDesc(value string) *PrometheusRuleApplyConfiguration {
	b.RuleItemBasesApplyConfiguration.Desc = &value
	return b
}

// WithLevel sets the Level field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Level field is set to the value of the last call.
func (b *PrometheusRuleApplyConfiguration) WithLevel(value kubeeyev1alpha2.Level) *PrometheusRuleApplyConfiguration {
	b.RuleItemBasesApplyConfiguration.Level = &value
	return b
}

// WithPrometheus sets the Prometheus field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Prometheus field is set to the value of the last call.
func (b *PrometheusRuleApplyConfiguration) WithPrometheus(value *PrometheusConfigApplyConfiguration) *PrometheusRuleApplyConfiguration {
	b.Prometheus = value
	return b
}

// WithRawDataEnabled sets the RawDataEnabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RawDataEnabled field is set to the value of the last call.
func (b *PrometheusRuleApplyConfiguration) WithRawDataEnabled(value bool) *PrometheusRuleApplyConfiguration {
	b.RawDataEnabled = &value
	return b
}
