apiVersion: kubeeye.kubesphere.io/v1alpha2
kind: InspectRule
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: kubeeye
    app.kubernetes.io/instance: inspectrules-sample
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: inspectrules
    app.kubernetes.io/part-of: kubeeye
    kubeeye.kubesphere.io/rule-tag: kubeeye_events_rego
  name: kubeeye-inspectrules0-1680158867
  namespace: kubeeye-system
spec:
  opas:
  - module: kubeeye_events_rego
    name: ExceptionEventsRule
    rule: |-
      package kubeeye_events_rego

      deny[msg] {
          resource := input
          type := resource.Object.kind
          resourcename := resource.Object.metadata.name
          resourcenamespace := resource.Object.metadata.namespace
          type == "Event"
          level := "warning"
          Message := resource.Object.reason
          Reason := resource.Object.message

          resource.Object.type != "Normal"

          msg := {
              "Name": sprintf("%v", [resourcename]),
              "Namespace": sprintf("%v", [resourcenamespace]),
              "Type": sprintf("%v", [type]),
              "Level": sprintf("%v", [level]),
              "Message": sprintf("%v", [Message]),
              "Reason": sprintf("%v", [Reason]),
          }
      }
status:
  importTime: null
