/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha2

import (
	context "context"

	kubeeyev1alpha2 "github.com/kubesphere/kubeeye/apis/kubeeye/v1alpha2"
	applyconfigurationkubeeyev1alpha2 "github.com/kubesphere/kubeeye/clients/applyconfiguration/kubeeye/v1alpha2"
	scheme "github.com/kubesphere/kubeeye/clients/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// InspectPlansGetter has a method to return a InspectPlanInterface.
// A group's client should implement this interface.
type InspectPlansGetter interface {
	InspectPlans() InspectPlanInterface
}

// InspectPlanInterface has methods to work with InspectPlan resources.
type InspectPlanInterface interface {
	Create(ctx context.Context, inspectPlan *kubeeyev1alpha2.InspectPlan, opts v1.CreateOptions) (*kubeeyev1alpha2.InspectPlan, error)
	Update(ctx context.Context, inspectPlan *kubeeyev1alpha2.InspectPlan, opts v1.UpdateOptions) (*kubeeyev1alpha2.InspectPlan, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, inspectPlan *kubeeyev1alpha2.InspectPlan, opts v1.UpdateOptions) (*kubeeyev1alpha2.InspectPlan, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*kubeeyev1alpha2.InspectPlan, error)
	List(ctx context.Context, opts v1.ListOptions) (*kubeeyev1alpha2.InspectPlanList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *kubeeyev1alpha2.InspectPlan, err error)
	Apply(ctx context.Context, inspectPlan *applyconfigurationkubeeyev1alpha2.InspectPlanApplyConfiguration, opts v1.ApplyOptions) (result *kubeeyev1alpha2.InspectPlan, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, inspectPlan *applyconfigurationkubeeyev1alpha2.InspectPlanApplyConfiguration, opts v1.ApplyOptions) (result *kubeeyev1alpha2.InspectPlan, err error)
	InspectPlanExpansion
}

// inspectPlans implements InspectPlanInterface
type inspectPlans struct {
	*gentype.ClientWithListAndApply[*kubeeyev1alpha2.InspectPlan, *kubeeyev1alpha2.InspectPlanList, *applyconfigurationkubeeyev1alpha2.InspectPlanApplyConfiguration]
}

// newInspectPlans returns a InspectPlans
func newInspectPlans(c *KubeeyeV1alpha2Client) *inspectPlans {
	return &inspectPlans{
		gentype.NewClientWithListAndApply[*kubeeyev1alpha2.InspectPlan, *kubeeyev1alpha2.InspectPlanList, *applyconfigurationkubeeyev1alpha2.InspectPlanApplyConfiguration](
			"inspectplans",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *kubeeyev1alpha2.InspectPlan { return &kubeeyev1alpha2.InspectPlan{} },
			func() *kubeeyev1alpha2.InspectPlanList { return &kubeeyev1alpha2.InspectPlanList{} },
		),
	}
}
