/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha2

import (
	context "context"

	kubeeyev1alpha2 "github.com/kubesphere/kubeeye/apis/kubeeye/v1alpha2"
	applyconfigurationkubeeyev1alpha2 "github.com/kubesphere/kubeeye/clients/applyconfiguration/kubeeye/v1alpha2"
	scheme "github.com/kubesphere/kubeeye/clients/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// InspectResultsGetter has a method to return a InspectResultInterface.
// A group's client should implement this interface.
type InspectResultsGetter interface {
	InspectResults() InspectResultInterface
}

// InspectResultInterface has methods to work with InspectResult resources.
type InspectResultInterface interface {
	Create(ctx context.Context, inspectResult *kubeeyev1alpha2.InspectResult, opts v1.CreateOptions) (*kubeeyev1alpha2.InspectResult, error)
	Update(ctx context.Context, inspectResult *kubeeyev1alpha2.InspectResult, opts v1.UpdateOptions) (*kubeeyev1alpha2.InspectResult, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, inspectResult *kubeeyev1alpha2.InspectResult, opts v1.UpdateOptions) (*kubeeyev1alpha2.InspectResult, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*kubeeyev1alpha2.InspectResult, error)
	List(ctx context.Context, opts v1.ListOptions) (*kubeeyev1alpha2.InspectResultList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *kubeeyev1alpha2.InspectResult, err error)
	Apply(ctx context.Context, inspectResult *applyconfigurationkubeeyev1alpha2.InspectResultApplyConfiguration, opts v1.ApplyOptions) (result *kubeeyev1alpha2.InspectResult, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, inspectResult *applyconfigurationkubeeyev1alpha2.InspectResultApplyConfiguration, opts v1.ApplyOptions) (result *kubeeyev1alpha2.InspectResult, err error)
	InspectResultExpansion
}

// inspectResults implements InspectResultInterface
type inspectResults struct {
	*gentype.ClientWithListAndApply[*kubeeyev1alpha2.InspectResult, *kubeeyev1alpha2.InspectResultList, *applyconfigurationkubeeyev1alpha2.InspectResultApplyConfiguration]
}

// newInspectResults returns a InspectResults
func newInspectResults(c *KubeeyeV1alpha2Client) *inspectResults {
	return &inspectResults{
		gentype.NewClientWithListAndApply[*kubeeyev1alpha2.InspectResult, *kubeeyev1alpha2.InspectResultList, *applyconfigurationkubeeyev1alpha2.InspectResultApplyConfiguration](
			"inspectresults",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *kubeeyev1alpha2.InspectResult { return &kubeeyev1alpha2.InspectResult{} },
			func() *kubeeyev1alpha2.InspectResultList { return &kubeeyev1alpha2.InspectResultList{} },
		),
	}
}
