/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha2

import (
	"context"
	"time"

	v1alpha2 "github.com/kubesphere/kubeeye/apis/kubeeye/v1alpha2"
	scheme "github.com/kubesphere/kubeeye/clients/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// InspectRulesesGetter has a method to return a InspectRulesInterface.
// A group's client should implement this options.
type InspectRulesesGetter interface {
	InspectRules(namespace string) InspectRulesInterface
}

// InspectRulesInterface has methods to work with InspectRule resources.
type InspectRulesInterface interface {
	Create(ctx context.Context, inspectRules *v1alpha2.InspectRule, opts v1.CreateOptions) (*v1alpha2.InspectRule, error)
	Update(ctx context.Context, inspectRules *v1alpha2.InspectRule, opts v1.UpdateOptions) (*v1alpha2.InspectRule, error)
	UpdateStatus(ctx context.Context, inspectRules *v1alpha2.InspectRule, opts v1.UpdateOptions) (*v1alpha2.InspectRule, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha2.InspectRule, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha2.InspectRuleList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha2.InspectRule, err error)
	InspectRulesExpansion
}

// inspectRuleses implements InspectRulesInterface
type inspectRuleses struct {
	client rest.Interface
	ns     string
}

// newInspectRuleses returns a InspectRule
func newInspectRuleses(c *KubeeyeV1alpha2Client, namespace string) *inspectRuleses {
	return &inspectRuleses{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the inspectRules, and returns the corresponding inspectRules object, and an error if there is any.
func (c *inspectRuleses) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha2.InspectRule, err error) {
	result = &v1alpha2.InspectRule{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("inspectrules").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of InspectRule that match those selectors.
func (c *inspectRuleses) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha2.InspectRuleList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha2.InspectRuleList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("inspectrules").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested inspectRuleses.
func (c *inspectRuleses) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("inspectrules").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a inspectRules and creates it.  Returns the server's representation of the inspectRules, and an error, if there is any.
func (c *inspectRuleses) Create(ctx context.Context, inspectRules *v1alpha2.InspectRule, opts v1.CreateOptions) (result *v1alpha2.InspectRule, err error) {
	result = &v1alpha2.InspectRule{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("inspectrules").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(inspectRules).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a inspectRules and updates it. Returns the server's representation of the inspectRules, and an error, if there is any.
func (c *inspectRuleses) Update(ctx context.Context, inspectRules *v1alpha2.InspectRule, opts v1.UpdateOptions) (result *v1alpha2.InspectRule, err error) {
	result = &v1alpha2.InspectRule{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("inspectrules").
		Name(inspectRules.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(inspectRules).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *inspectRuleses) UpdateStatus(ctx context.Context, inspectRules *v1alpha2.InspectRule, opts v1.UpdateOptions) (result *v1alpha2.InspectRule, err error) {
	result = &v1alpha2.InspectRule{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("inspectrules").
		Name(inspectRules.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(inspectRules).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the inspectRules and deletes it. Returns an error if one occurs.
func (c *inspectRuleses) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("inspectrules").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *inspectRuleses) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("inspectrules").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched inspectRules.
func (c *inspectRuleses) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha2.InspectRule, err error) {
	result = &v1alpha2.InspectRule{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("inspectrules").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
