/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha2

import (
	"context"
	"time"

	v1alpha2 "github.com/kubesphere/kubeeye-v1alpha2/apis/kubeeye/v1alpha2"
	scheme "github.com/kubesphere/kubeeye-v1alpha2/clients/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// InspectRulesGetter has a method to return a InspectRuleInterface.
// A group's client should implement this interface.
type InspectRulesGetter interface {
	InspectRules() InspectRuleInterface
}

// InspectRuleInterface has methods to work with InspectRule resources.
type InspectRuleInterface interface {
	Create(ctx context.Context, inspectRule *v1alpha2.InspectRule, opts v1.CreateOptions) (*v1alpha2.InspectRule, error)
	Update(ctx context.Context, inspectRule *v1alpha2.InspectRule, opts v1.UpdateOptions) (*v1alpha2.InspectRule, error)
	UpdateStatus(ctx context.Context, inspectRule *v1alpha2.InspectRule, opts v1.UpdateOptions) (*v1alpha2.InspectRule, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha2.InspectRule, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha2.InspectRuleList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha2.InspectRule, err error)
	InspectRuleExpansion
}

// inspectRules implements InspectRuleInterface
type inspectRules struct {
	client rest.Interface
}

// newInspectRules returns a InspectRules
func newInspectRules(c *KubeeyeV1alpha2Client) *inspectRules {
	return &inspectRules{
		client: c.RESTClient(),
	}
}

// Get takes name of the inspectRule, and returns the corresponding inspectRule object, and an error if there is any.
func (c *inspectRules) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha2.InspectRule, err error) {
	result = &v1alpha2.InspectRule{}
	err = c.client.Get().
		Resource("inspectrules").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of InspectRules that match those selectors.
func (c *inspectRules) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha2.InspectRuleList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha2.InspectRuleList{}
	err = c.client.Get().
		Resource("inspectrules").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested inspectRules.
func (c *inspectRules) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("inspectrules").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a inspectRule and creates it.  Returns the server's representation of the inspectRule, and an error, if there is any.
func (c *inspectRules) Create(ctx context.Context, inspectRule *v1alpha2.InspectRule, opts v1.CreateOptions) (result *v1alpha2.InspectRule, err error) {
	result = &v1alpha2.InspectRule{}
	err = c.client.Post().
		Resource("inspectrules").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(inspectRule).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a inspectRule and updates it. Returns the server's representation of the inspectRule, and an error, if there is any.
func (c *inspectRules) Update(ctx context.Context, inspectRule *v1alpha2.InspectRule, opts v1.UpdateOptions) (result *v1alpha2.InspectRule, err error) {
	result = &v1alpha2.InspectRule{}
	err = c.client.Put().
		Resource("inspectrules").
		Name(inspectRule.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(inspectRule).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *inspectRules) UpdateStatus(ctx context.Context, inspectRule *v1alpha2.InspectRule, opts v1.UpdateOptions) (result *v1alpha2.InspectRule, err error) {
	result = &v1alpha2.InspectRule{}
	err = c.client.Put().
		Resource("inspectrules").
		Name(inspectRule.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(inspectRule).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the inspectRule and deletes it. Returns an error if one occurs.
func (c *inspectRules) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("inspectrules").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *inspectRules) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("inspectrules").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched inspectRule.
func (c *inspectRules) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha2.InspectRule, err error) {
	result = &v1alpha2.InspectRule{}
	err = c.client.Patch(pt).
		Resource("inspectrules").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
